### PR TITLE
Implemented Selected Element Dropdown Feature

### PR DESCRIPTION
**Pull request by manibabubendalam**
1. If enableNodeTypeChangeSelection flag is enabled, then selected element dropdown feature will be shown. It will be shown in Recorder Sequence screen.

### CODE REVIEW

**Comment by manibabubendalam** [comment]
1. To fix the errors occurring while recording, I have merged issue-380 into react-typescript branch

**Comment by manibabubendalam** [comment]
Merged with latest changes from Digital-Assistant/Digital_Assistant_Client/react-typescript branch

**Comment by yureshwar** [comment]
Change the flag from config to customconfig and give a new pull request

**Comment by manibabubendalam** [comment]
1. enableNodeTypeSelection flag is referenced from CustomConfig file

**Comment by yureshwar** [comment]
Added changes to the codebase of manibabu and merged the code.

**Pull request merged**
